# Generated by Django 3.1 on 2022-12-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerhome',
            name='title_des',
            field=models.TextField(verbose_name="Qisqacha ma'lumot"),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Qisqacha malumot'),
        ),
        migrations.AlterField(
            model_name='product',
            name='maxsulot_haqida',
            field=models.TextField(blank=True, null=True),
        ),
    ]
